name: DojoDirector
version: 1.0.0
main: com.megabyte6.dojodirector.DojoDirector
api-version: '1.20'
commands:
  dojo:
    description: Customized commands to manage the minecraft server at Code Ninjas.
    usage: /dojo
    aliases: dj
    permission: op
